# Class: stns::server::config
# ===========================
#
# stns::server::config is to configure stns.

class stns::server::config {

  $port     = $stns::server::port
  $user     = $stns::server::user
  $password = $stns::server::password
  $users    = $stns::server::users
  $groups   = $stns::server::groups

  file { '/etc/stns/stns.conf':
    ensure  => present,
    owner   => 'root',
    group   => 'root',
    mode    => '0644',
    content => template('stns/stns.conf.erb'),
    notify  => Class['stns::server::service'],
  }

  concat {
    '/etc/stns/conf.d/groups.conf':
      ensure => present,
      owner  => 'root',
      group  => 'root',
      mode   => '0644';

    '/etc/stns/conf.d/users.conf':
      ensure => present,
      owner  => 'root',
      group  => 'root',
      mode   => '0644';
  }

  $header = "# HEADER: Autogenerated by Puppet.\n\n"

  concat::fragment {
    'groups_header':
      target  => '/etc/stns/conf.d/groups.conf',
      content => $header,
      order   => '01';

    'users_header':
      target  => '/etc/stns/conf.d/users.conf',
      content => $header,
      order   => '01';
  }

}
